
package my_form;

import java.awt.Color;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;


/**
 *
 * @author snamiracle
 */
public class AddMemberForm extends javax.swing.JFrame {

    /**
     * Creates new form ManageGenresForm
     */
    
    my_class.Func_Class func = new my_class.Func_Class();
    my_class.Member member = new my_class.Member();
    String imagePath = null;
    
    
    public AddMemberForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Border panelHeaderBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(1,152,117));
        jPanel1.setBorder(panelHeaderBorder);
        
        lblEmptyFname.setVisible(false);
        lblEmptyLname.setVisible(false);
        lblEmptyNumber.setVisible(false);
        
        func.displayImage(60, 60,null, "/images/membericon.png", lblTitleMember);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitleMember = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMemFname = new javax.swing.JTextField();
        btnAddMem = new javax.swing.JButton();
        lblEmptyFname = new javax.swing.JLabel();
        txtMemLname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblEmptyLname = new javax.swing.JLabel();
        txtMemPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblEmptyNumber = new javax.swing.JLabel();
        txtMemEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbGender = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        lblImagePath = new javax.swing.JLabel();
        btnSelectProfile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitleMember.setBackground(new java.awt.Color(1, 152, 117));
        lblTitleMember.setFont(new java.awt.Font("AvertaStd-Black", 0, 24)); // NOI18N
        lblTitleMember.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleMember.setText("Add Member");
        lblTitleMember.setOpaque(true);

        lblClose.setBackground(new java.awt.Color(1, 152, 117));
        lblClose.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel3.setText("First Name:");

        txtMemFname.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        btnAddMem.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        btnAddMem.setText("Add New Member");
        btnAddMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMemActionPerformed(evt);
            }
        });

        lblEmptyFname.setForeground(new java.awt.Color(255, 0, 0));
        lblEmptyFname.setText("*enter the first name");
        lblEmptyFname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmptyFnameMouseClicked(evt);
            }
        });

        txtMemLname.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel4.setText("Last Name:");

        lblEmptyLname.setForeground(new java.awt.Color(255, 0, 0));
        lblEmptyLname.setText("*enter the last name");
        lblEmptyLname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmptyLnameMouseClicked(evt);
            }
        });

        txtMemPhone.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtMemPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMemPhoneKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel5.setText("Phone Number:");

        lblEmptyNumber.setForeground(new java.awt.Color(255, 0, 0));
        lblEmptyNumber.setText("*enter the phone number");
        lblEmptyNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmptyNumberMouseClicked(evt);
            }
        });

        txtMemEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel7.setText("Email:");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel8.setText("Gender:");

        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel9.setText("Profile Picture:");

        lblImagePath.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblImagePath.setForeground(new java.awt.Color(0, 51, 255));
        lblImagePath.setText("choose profile picture...");

        btnSelectProfile.setText("select profile");
        btnSelectProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitleMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSelectProfile))
                            .addComponent(jLabel5)
                            .addComponent(txtMemPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(lblEmptyLname)
                            .addComponent(lblEmptyNumber)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtMemFname, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMemLname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)
                                .addComponent(txtMemEmail)
                                .addComponent(lblEmptyFname, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddMem, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleMember, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMemFname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmptyFname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMemLname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmptyLname, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMemPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmptyNumber)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMemEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImagePath)
                    .addComponent(btnSelectProfile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnAddMem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    //add
    private void btnAddMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMemActionPerformed
        // TODO add your handling code here:
        
        lblEmptyFname.setVisible(false);
        lblEmptyLname.setVisible(false);
        lblEmptyNumber.setVisible(false);
        
        String fname = txtMemFname.getText();
        String lname = txtMemLname.getText();
        String number = txtMemPhone.getText();
        String email = txtMemEmail.getText();
        String gender = cbGender.getSelectedItem().toString();
        
        if(fname.trim().isEmpty()){
            lblEmptyFname.setVisible(true);
        }else if(lname.trim().isEmpty()){
            lblEmptyLname.setVisible(true);
        }else if(number.trim().isEmpty()){
            lblEmptyNumber.setVisible(true);
        }
        else{
            byte[] img = null;
            
            if(imagePath != null){
                
                try {
                    
                    Path path = Paths.get(imagePath);
                    img = Files.readAllBytes(path);
                    member.addMember(fname, lname, number, email, gender, img);
                    
                } catch (IOException ex) {
                    Logger.getLogger(AddMemberForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Select a Profile for this Member" , "No Picture Selected", 2);
            }
        }
    }//GEN-LAST:event_btnAddMemActionPerformed

    private void lblEmptyFnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmptyFnameMouseClicked
        // TODO add your handling code here:
        lblEmptyFname.setVisible(false);
    }//GEN-LAST:event_lblEmptyFnameMouseClicked

    private void lblEmptyLnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmptyLnameMouseClicked
        // TODO add your handling code here:
        lblEmptyLname.setVisible(false);
    }//GEN-LAST:event_lblEmptyLnameMouseClicked

    private void lblEmptyNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmptyNumberMouseClicked
        // TODO add your handling code here:
        lblEmptyNumber.setVisible(false);
    }//GEN-LAST:event_lblEmptyNumberMouseClicked

    private void btnSelectProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectProfileActionPerformed
        // TODO add your handling code here:
        String path = func.selectImage();
        lblImagePath.setText(path);
        imagePath = path;
        
    }//GEN-LAST:event_btnSelectProfileActionPerformed

    private void txtMemPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMemPhoneKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtMemPhoneKeyTyped
      
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMemberForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMem;
    private javax.swing.JButton btnSelectProfile;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblEmptyFname;
    private javax.swing.JLabel lblEmptyLname;
    private javax.swing.JLabel lblEmptyNumber;
    private javax.swing.JLabel lblImagePath;
    private javax.swing.JLabel lblTitleMember;
    private javax.swing.JTextField txtMemEmail;
    private javax.swing.JTextField txtMemFname;
    private javax.swing.JTextField txtMemLname;
    private javax.swing.JTextField txtMemPhone;
    // End of variables declaration//GEN-END:variables
}
