
package my_form;

import java.awt.Color;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import my_class.Member;

/**
 *
 * @author snamiracle
 */
public class EditMemberForm extends javax.swing.JFrame {

    /**
     * Creates new form ManageGenresForm
     */
    
    my_class.Func_Class func = new my_class.Func_Class();
    my_class.Member member = new my_class.Member();
    String imagePath = null;
    
    
    public EditMemberForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Border panelHeaderBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(1,152,117));
        jPanel1.setBorder(panelHeaderBorder);
        
//        Border lblImageBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(0,0,0));
//        lblImage.setBorder(lblImageBorder);
        
        lblEmptyFname.setVisible(false);
        lblEmptyLname.setVisible(false);
        lblEmptyNumber.setVisible(false);
        
        func.displayImage(60, 60,null, "/images/membericon.png", lblTitleMember);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagePath = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTitleMember = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMemFname = new javax.swing.JTextField();
        btnEditMem = new javax.swing.JButton();
        lblEmptyFname = new javax.swing.JLabel();
        txtMemLname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblEmptyLname = new javax.swing.JLabel();
        txtMemPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblEmptyNumber = new javax.swing.JLabel();
        txtMemEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbGender = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnSelectProfile = new javax.swing.JButton();
        txtMemID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnSearchID = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        lblImagePath1 = new javax.swing.JLabel();

        lblImagePath.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblImagePath.setForeground(new java.awt.Color(0, 51, 255));
        lblImagePath.setText("choose profile picture...");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitleMember.setBackground(new java.awt.Color(1, 152, 117));
        lblTitleMember.setFont(new java.awt.Font("AvertaStd-Black", 0, 24)); // NOI18N
        lblTitleMember.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleMember.setText("Edit Member");
        lblTitleMember.setOpaque(true);

        lblClose.setBackground(new java.awt.Color(1, 152, 117));
        lblClose.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel3.setText("First Name:");

        txtMemFname.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        btnEditMem.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        btnEditMem.setText("Edit Member");
        btnEditMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditMemActionPerformed(evt);
            }
        });

        lblEmptyFname.setForeground(new java.awt.Color(255, 0, 0));
        lblEmptyFname.setText("*enter the first name");
        lblEmptyFname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmptyFnameMouseClicked(evt);
            }
        });

        txtMemLname.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel4.setText("Last Name:");

        lblEmptyLname.setForeground(new java.awt.Color(255, 0, 0));
        lblEmptyLname.setText("*enter the last name");
        lblEmptyLname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmptyLnameMouseClicked(evt);
            }
        });

        txtMemPhone.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtMemPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMemPhoneKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel5.setText("Phone Number:");

        lblEmptyNumber.setForeground(new java.awt.Color(255, 0, 0));
        lblEmptyNumber.setText("*enter the phone number");
        lblEmptyNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmptyNumberMouseClicked(evt);
            }
        });

        txtMemEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel7.setText("Email:");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel8.setText("Gender:");

        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel9.setText("Profile Picture:");

        btnSelectProfile.setText("select profile");
        btnSelectProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectProfileActionPerformed(evt);
            }
        });

        txtMemID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel6.setText("Enter Member ID:");

        btnSearchID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnSearchID.setText("search");
        btnSearchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchIDActionPerformed(evt);
            }
        });

        lblImage.setBackground(new java.awt.Color(255, 255, 255));
        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setOpaque(true);

        lblImagePath1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblImagePath1.setForeground(new java.awt.Color(0, 51, 255));
        lblImagePath1.setText("choose picture...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMemEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMemPhone)
                                    .addComponent(txtMemFname, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMemID))
                                    .addComponent(txtMemLname, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmptyFname)
                                    .addComponent(lblEmptyLname)
                                    .addComponent(lblEmptyNumber)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSelectProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(lblImagePath1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cbGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(55, 55, 55))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitleMember, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnEditMem, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleMember, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMemID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchID)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMemFname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(3, 3, 3)
                        .addComponent(txtMemLname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMemPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEmptyFname)
                        .addGap(28, 28, 28)
                        .addComponent(lblEmptyLname, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lblEmptyNumber)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMemEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSelectProfile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagePath1))
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEditMem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    //add
    private void btnEditMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditMemActionPerformed
        // TODO add your handling code here:
        
        lblEmptyFname.setVisible(false);
        lblEmptyLname.setVisible(false);
        lblEmptyNumber.setVisible(false);
        
        String fname = txtMemFname.getText();
        String lname = txtMemLname.getText();
        String number = txtMemPhone.getText();
        String email = txtMemEmail.getText();
        String gender = cbGender.getSelectedItem().toString();

        
        if(fname.trim().isEmpty()){
            lblEmptyFname.setVisible(true);
        }else if(lname.trim().isEmpty()){
            lblEmptyLname.setVisible(true);
        }else if(number.trim().isEmpty()){
            lblEmptyNumber.setVisible(true);
        }
        else{
            byte[] img = null;
            
            if(imagePath != null){
                
                try {
                    
                    Integer id = Integer.parseInt(txtMemID.getText());
                    Path path = Paths.get(imagePath);
                    img = Files.readAllBytes(path);
                    member.editMember(id, fname, lname, number, email, gender, img);
                    
                } catch (IOException | NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Make sure to enter the member ID & Select a Profile" , "No ID or Picture Selected", 2);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Select a Profile for this Member" , "No Picture Selected", 2);
            }
        }
    }//GEN-LAST:event_btnEditMemActionPerformed

    private void lblEmptyFnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmptyFnameMouseClicked
        // TODO add your handling code here:
        lblEmptyFname.setVisible(false);
    }//GEN-LAST:event_lblEmptyFnameMouseClicked

    private void lblEmptyLnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmptyLnameMouseClicked
        // TODO add your handling code here:
        lblEmptyLname.setVisible(false);
    }//GEN-LAST:event_lblEmptyLnameMouseClicked

    private void lblEmptyNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmptyNumberMouseClicked
        // TODO add your handling code here:
        lblEmptyNumber.setVisible(false);
    }//GEN-LAST:event_lblEmptyNumberMouseClicked

    private void btnSelectProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectProfileActionPerformed
        // TODO add your handling code here:
        String path = func.selectImage();
        lblImagePath1.setText(path);
        imagePath = path;
            
        func.displayImage(60, 60,null, imagePath, lblImage);
        
    }//GEN-LAST:event_btnSelectProfileActionPerformed

    private void btnSearchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchIDActionPerformed
        // TODO add your handling code here:
        
        Member SelectedMember;
        try {
            
            Integer id = Integer.parseInt(txtMemID.getText());
            
            SelectedMember = member.getMemberById(id);
            
            if(SelectedMember != null){
                txtMemID.setText(String.valueOf(SelectedMember.getId()));
                txtMemFname.setText(SelectedMember.getFirstName());
                txtMemLname.setText(SelectedMember.getLastname());
                txtMemPhone.setText(SelectedMember.getPhone());
                txtMemEmail.setText(SelectedMember.getEmail());
                cbGender.setSelectedItem(SelectedMember.getGender());
            
            byte[] image = SelectedMember.getPicture();
            
            func.displayImage(60, 60,image, "", lblImage);
            }else{
                JOptionPane.showMessageDialog(null, "No Member with this ID found", "Invalid ID",3);
            }
            
        } catch (SQLException | NumberFormatException ex) {
            //Logger.getLogger(EditMemberForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Enter a Valid Memeber ID", "Invalid ID",3);
        }
        
    }//GEN-LAST:event_btnSearchIDActionPerformed

    private void txtMemPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMemPhoneKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtMemPhoneKeyTyped
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditMem;
    private javax.swing.JButton btnSearchID;
    private javax.swing.JButton btnSelectProfile;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblEmptyFname;
    private javax.swing.JLabel lblEmptyLname;
    private javax.swing.JLabel lblEmptyNumber;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImagePath;
    private javax.swing.JLabel lblImagePath1;
    private javax.swing.JLabel lblTitleMember;
    private javax.swing.JTextField txtMemEmail;
    private javax.swing.JTextField txtMemFname;
    private javax.swing.JTextField txtMemID;
    private javax.swing.JTextField txtMemLname;
    private javax.swing.JTextField txtMemPhone;
    // End of variables declaration//GEN-END:variables
}
