/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my_form;

import java.awt.Color;
import java.awt.HeadlessException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author snamiracle
 */
public class IssueBookForm extends javax.swing.JFrame {

    /**
     * Creates new form MembersListForm
     */
    
    my_class.Member member = new my_class.Member();
    my_class.Func_Class func = new my_class.Func_Class();
    my_class.Book book = new my_class.Book();
    my_class.Issue_Book issue = new my_class.Issue_Book();
    
    boolean book_exist = false;
    boolean member_exist = false;
    
    
    String imagePath = "";
    
    public IssueBookForm() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        Border panelHeaderBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(183,77,59));
        jPanel1.setBorder(panelHeaderBorder);
        
        func.displayImage(65, 65,null, "/images/issuebookicon.png", lblTitleMember);
        
        
        setBorderToJlabel(lblBookName, Color.white);
        setBorderToJlabel(lblMemberName, Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();
        lblImagePath1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTitleMember = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnIssue = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        dateIssue = new com.toedter.calendar.JDateChooser();
        btnSearchBook = new javax.swing.JButton();
        lblBookName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblMemberName = new javax.swing.JLabel();
        btnSearchMember = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lblAvailable = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dateReturn = new com.toedter.calendar.JDateChooser();
        spBookId = new javax.swing.JSpinner();
        spMemberID = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextArea();

        lblImage.setBackground(new java.awt.Color(255, 255, 255));
        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setOpaque(true);

        lblImagePath1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblImagePath1.setForeground(new java.awt.Color(0, 51, 255));
        lblImagePath1.setText("choose picture...");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitleMember.setBackground(new java.awt.Color(183, 77, 59));
        lblTitleMember.setFont(new java.awt.Font("AvertaStd-Black", 0, 24)); // NOI18N
        lblTitleMember.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleMember.setText("Issue Book");
        lblTitleMember.setAlignmentY(0.0F);
        lblTitleMember.setOpaque(true);

        lblClose.setBackground(new java.awt.Color(183, 77, 59));
        lblClose.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel6.setText("Enter Book ID:");

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel12.setText("Issue Date:");

        btnIssue.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        btnIssue.setText("Issue");
        btnIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSearchBook.setText("search book");
        btnSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBookActionPerformed(evt);
            }
        });

        lblBookName.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblBookName.setForeground(new java.awt.Color(51, 51, 255));
        lblBookName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBookName.setText("Book Name");
        lblBookName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBookName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBookNameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBookNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBookNameMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel7.setText("Enter Member ID:");

        lblMemberName.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblMemberName.setForeground(new java.awt.Color(51, 51, 255));
        lblMemberName.setText("Member Full-Name");
        lblMemberName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMemberName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMemberNameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMemberNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMemberNameMouseExited(evt);
            }
        });

        btnSearchMember.setText("search member");
        btnSearchMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchMemberActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel10.setText("Is This Book Available:");

        lblAvailable.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblAvailable.setForeground(new java.awt.Color(51, 51, 255));
        lblAvailable.setText("Yes-or-No");

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel13.setText("Return Date:");

        spBookId.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        spMemberID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel14.setText("Note:");

        txtNote.setColumns(20);
        txtNote.setRows(5);
        jScrollPane1.setViewportView(txtNote);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitleMember, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAvailable))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(dateReturn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dateIssue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMemberName)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spBookId, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                    .addComponent(lblBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spMemberID))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearchMember))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitleMember, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchBook)
                    .addComponent(spBookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchMember)
                    .addComponent(jLabel7)
                    .addComponent(spMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblAvailable))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(dateIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(dateReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBookActionPerformed
    
        int book_id = (int)spBookId.getValue();
        
        try {
            my_class.Book selectedBook = book.getBookById(book_id);
            
            if(selectedBook != null){
                lblBookName.setText(selectedBook.getName());
                book_exist = true;
                if(issue.checkBookAvailability(book_id)){
                   lblAvailable.setText("Yes");
                   lblAvailable.setForeground(Color.green);
                }else{
                    lblAvailable.setText("No");
                    lblAvailable.setForeground(Color.red);
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "This book doesn't exist","Book Not Found",2);
                lblBookName.setText("Book Name");
                book_exist = false;
                lblAvailable.setText("Yes-or_No");
                lblAvailable.setForeground(new Color(51,51,255));

            }
        } catch (SQLException ex) {
            Logger.getLogger(IssueBookForm.class.getName()).log(Level.SEVERE, null, ex);
        
        }

    }//GEN-LAST:event_btnSearchBookActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueActionPerformed
        int _book_id = (int)spBookId.getValue();
        int _member_id = (int)spMemberID.getValue();
        String note = txtNote.getText();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        try{
            String _issue_date = dateFormat.format(dateIssue.getDate());
            String _return_date = dateFormat.format(dateReturn.getDate());
            
            Date issDate = dateFormat.parse(_issue_date);
            Date rtnDate = dateFormat.parse(_return_date);
            
            if(!book_exist){
                JOptionPane.showMessageDialog(null, "You need to check if this book exist first by clicking Search","Check if the book exist",2);
            }else if(!member_exist){
                JOptionPane.showMessageDialog(null, "You need to check if this member exist first by clicking Search","Check if the member exist",2);
            }else if(!issue.checkBookAvailability(_book_id)){
                JOptionPane.showMessageDialog(null, "This book is not Available right now","Book not Available",2);
            }
            else if(rtnDate.before(issDate)){
                JOptionPane.showMessageDialog(null, "The return Date must be after Issue date","Wrong Return Date",2);
            }else{
                issue.addIssue(_book_id, _member_id, "issued", _issue_date, _return_date, note);
                spBookId.setValue(0);
                spMemberID.setValue(0);
                lblBookName.setText("Book Name");
                lblMemberName.setText("Member Full-Name");
                lblAvailable.setText("Yes-or-No");
                lblAvailable.setForeground(new Color(51,102,255));
                dateIssue.setDate(new Date());
                dateReturn.setDate(new Date());
                book_exist = false;
                member_exist = false;
            }
            
        } catch(HeadlessException | NullPointerException | ParseException ex){
            JOptionPane.showMessageDialog(null, "Select Issue Date & Return Date","Select Date",2);
        }
    }//GEN-LAST:event_btnIssueActionPerformed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnSearchMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchMemberActionPerformed
        // TODO add your handling code here:
        int member_id = (int)spMemberID.getValue();
        
        try {
            my_class.Member selectedMember = member.getMemberById(member_id);
            
            if(selectedMember != null){
                lblMemberName.setText(selectedMember.getFirstName() + " " + selectedMember.getLastname());
                member_exist = true;
            }else{
                JOptionPane.showMessageDialog(null, "This member doesn't exist","Member Not Found",2);
                lblMemberName.setText("Member Full-Name");
                member_exist = false;

            }
        } catch (SQLException ex) {
            Logger.getLogger(IssueBookForm.class.getName()).log(Level.SEVERE, null, ex);
        
        }
    }//GEN-LAST:event_btnSearchMemberActionPerformed

    private void lblBookNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBookNameMouseClicked
        // TODO add your handling code here:
        int book_id = (int)spBookId.getValue();
        BookInfoForm bookInfo = new BookInfoForm(book_id);
        bookInfo.setVisible(true);
    }//GEN-LAST:event_lblBookNameMouseClicked

    private void lblMemberNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMemberNameMouseClicked
        // TODO add your handling code here:
        int member_id = (int)spMemberID.getValue();
        MemberInfoForm memberInfo = new MemberInfoForm(member_id);
        memberInfo.setVisible(true);
    }//GEN-LAST:event_lblMemberNameMouseClicked

    private void lblBookNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBookNameMouseEntered
        // TODO add your handling code here:
        setBorderToJlabel(lblBookName, new Color(51,102,255));
    }//GEN-LAST:event_lblBookNameMouseEntered

    private void lblBookNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBookNameMouseExited
        // TODO add your handling code here:
        setBorderToJlabel(lblBookName, Color.white);
    }//GEN-LAST:event_lblBookNameMouseExited

    private void lblMemberNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMemberNameMouseEntered
        // TODO add your handling code here:
        setBorderToJlabel(lblMemberName, new Color(51,102,255));
    }//GEN-LAST:event_lblMemberNameMouseEntered

    private void lblMemberNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMemberNameMouseExited
        // TODO add your handling code here:
        setBorderToJlabel(lblMemberName, Color.white);
    }//GEN-LAST:event_lblMemberNameMouseExited

    public void setBorderToJlabel(JLabel lable, Color color){
        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, color);
        lable.setBorder(border);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnIssue;
    private javax.swing.JButton btnSearchBook;
    private javax.swing.JButton btnSearchMember;
    private com.toedter.calendar.JDateChooser dateIssue;
    private com.toedter.calendar.JDateChooser dateReturn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvailable;
    private javax.swing.JLabel lblBookName;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImagePath1;
    private javax.swing.JLabel lblMemberName;
    private javax.swing.JLabel lblTitleMember;
    private javax.swing.JSpinner spBookId;
    private javax.swing.JSpinner spMemberID;
    private javax.swing.JTextArea txtNote;
    // End of variables declaration//GEN-END:variables
}
