
package my_form;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author snamiracle
 */
public class ManageUsersForm extends javax.swing.JFrame {

    /**
     * Creates new form ManageGenresForm
     */
    
    my_class.Func_Class func = new my_class.Func_Class();
    my_class.Users user = new my_class.Users();
    
    public ManageUsersForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Border panelHeaderBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(178,45,91));
        jPanel1.setBorder(panelHeaderBorder);
        
        func.customTable(tblUser);
        
        func.customTableHeader(tblUser, new Color(34,167,240),15);
        
        lblEmptyFname.setForeground(Color.white);
        lblEmptyLname.setForeground(Color.white);
        lblEmptyUname.setForeground(Color.white);
        lblEmptyPwd.setForeground(Color.white);
        
        func.displayImage(70, 70,null, "/images/manageusericon.png", lblTitle);
        
        populateJtableWithUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        lblEmptyFname = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblEmptyLname = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPwd = new javax.swing.JPasswordField();
        txtCfPwd = new javax.swing.JPasswordField();
        lblEmptyUname = new javax.swing.JLabel();
        lblEmptyPwd = new javax.swing.JLabel();
        chkAdmin = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(955, 677));

        lblTitle.setBackground(new java.awt.Color(178, 45, 91));
        lblTitle.setFont(new java.awt.Font("AvertaStd-Black", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Manage Users");
        lblTitle.setOpaque(true);

        lblClose.setBackground(new java.awt.Color(178, 45, 91));
        lblClose.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel3.setText("First Name:");

        txtId.setEnabled(false);

        txtFname.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblUser.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUser);

        lblEmptyFname.setForeground(new java.awt.Color(255, 0, 0));
        lblEmptyFname.setText("*enter the first name");
        lblEmptyFname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmptyFnameMouseClicked(evt);
            }
        });

        txtLname.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel4.setText("Last Name:");

        lblEmptyLname.setForeground(new java.awt.Color(255, 0, 0));
        lblEmptyLname.setText("*enter the last name");
        lblEmptyLname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmptyLnameMouseClicked(evt);
            }
        });

        txtUser.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel5.setText("Username:");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel7.setText("Password:");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel8.setText("Confirm password:");

        txtPwd.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        txtCfPwd.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        lblEmptyUname.setForeground(new java.awt.Color(255, 0, 0));
        lblEmptyUname.setText("*enter the username");
        lblEmptyUname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmptyUnameMouseClicked(evt);
            }
        });

        lblEmptyPwd.setForeground(new java.awt.Color(255, 0, 0));
        lblEmptyPwd.setText("*enter the password");
        lblEmptyPwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmptyPwdMouseClicked(evt);
            }
        });

        chkAdmin.setText("Make to Admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblEmptyPwd)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPwd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblEmptyUname)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chkAdmin)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFname, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(txtLname)
                            .addComponent(lblEmptyLname)
                            .addComponent(jLabel8)
                            .addComponent(txtCfPwd)
                            .addComponent(lblEmptyFname))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmptyFname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmptyLname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmptyUname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmptyPwd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCfPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(chkAdmin)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    //add
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        lblEmptyFname.setForeground(Color.white);
        lblEmptyLname.setForeground(Color.white);
        lblEmptyUname.setForeground(Color.white);
        lblEmptyPwd.setForeground(Color.white);
        
        String fname = txtFname.getText();
        String lname = txtLname.getText();
        String username = txtUser.getText();
        String password = String.valueOf(txtPwd.getPassword());
        String cfPassword = String.valueOf(txtCfPwd.getPassword());
        String userType = "user";
        
        if(chkAdmin.isSelected()){
            userType = "admin";
        }
        
        if(fname.trim().isEmpty()){
            lblEmptyFname.setForeground(Color.red);
        }else if(lname.trim().isEmpty()){  
            lblEmptyLname.setForeground(Color.red);
        }else if(username.trim().isEmpty()){
            lblEmptyUname.setForeground(Color.red);
        }else if(password.trim().isEmpty()){
            lblEmptyPwd.setForeground(Color.red);
        }else if(!password.equals(cfPassword)){
            JOptionPane.showMessageDialog(null, "Password not Match!","password error",0);
            //lblEmptyCfPwd.setForeground(Color.red);
        }else if(user.checkUsernameExists(0,username)){
            JOptionPane.showMessageDialog(null, "This user already existed.","user existed",0);

        }else{
            user.addUser(fname,lname,username,cfPassword,userType);
            populateJtableWithUsers();
            txtId.setText("");
            txtFname.setText("");
            txtLname.setText("");
            txtUser.setText("");
            txtPwd.setText("");
            txtCfPwd.setText("");
            chkAdmin.setSelected(false);
            
            hideLabel();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    //edit
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        
        lblEmptyFname.setForeground(Color.white);
        lblEmptyLname.setForeground(Color.white);
        lblEmptyUname.setForeground(Color.white);
        lblEmptyPwd.setForeground(Color.white);
        
        String fname = txtFname.getText();
        String lname = txtLname.getText();
        String username = txtUser.getText();
        String password = String.valueOf(txtPwd.getPassword());
        String cfPassword = String.valueOf(txtCfPwd.getPassword());
        String userType = "user";
        
        if(chkAdmin.isSelected()){
            userType = "admin";
        }
        
        if(fname.trim().isEmpty()){
            lblEmptyFname.setForeground(Color.red);
        }else if(lname.trim().isEmpty()){  
            lblEmptyLname.setForeground(Color.red);
        }else if(username.trim().isEmpty()){
            lblEmptyUname.setForeground(Color.red);
        }else if(password.trim().isEmpty()){
            lblEmptyPwd.setForeground(Color.red);
        }else if(!password.equals(cfPassword)){
            JOptionPane.showMessageDialog(null, "Password not Match!","password error",0);
            //lblEmptyCfPwd.setForeground(Color.red);
        }else{
            
            try{
                int id = Integer.parseInt(txtId.getText());

                if(user.checkUsernameExists(id,username)){
                JOptionPane.showMessageDialog(null, "This user already existed.","user existed",0);

            }else{
                user.editUser(id,fname,lname,username,cfPassword,userType);
                populateJtableWithUsers(); 
                txtId.setText("");
                txtFname.setText("");
                txtLname.setText("");
                txtUser.setText("");
                txtPwd.setText("");
                txtCfPwd.setText("");
                chkAdmin.setSelected(false);
                
                hideLabel();
                }


            } catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Select user to edit","No user selected",0);

            }
            
        }
    }//GEN-LAST:event_btnEditActionPerformed

    //delete
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
            // TODO add your handling code here:
        try{
                int id = Integer.parseInt(txtId.getText());
                
                int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this User?", "Confirm",JOptionPane.YES_NO_OPTION);
            
                if(confirm == JOptionPane.YES_OPTION){
                    user.removeUser(id);
                }
                
                populateJtableWithUsers();
                txtId.setText("");
                txtFname.setText("");
                txtLname.setText("");
                txtUser.setText("");
                txtPwd.setText("");
                txtCfPwd.setText("");
                chkAdmin.setSelected(false);
                
                hideLabel();
            }
            catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Invalid User ID", "error", 0);
            }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMouseClicked
        // TODO add your handling code here:
        int index = tblUser.getSelectedRow();
        String id = tblUser.getValueAt(index, 0).toString();
        String firstName = tblUser.getValueAt(index, 1).toString();
        String lastName = tblUser.getValueAt(index, 2).toString();
        String username = tblUser.getValueAt(index, 3).toString();
        String password = tblUser.getValueAt(index, 4).toString();
        String userType= tblUser.getValueAt(index, 5).toString();
        
        txtId.setText(id);
        txtFname.setText(firstName);
        txtLname.setText(lastName);
        txtUser.setText(username);
        txtPwd.setText(password);
        txtCfPwd.setText(password);
        
        if(userType.equals("admin")){
            chkAdmin.setSelected(true);
        }else{
            chkAdmin.setSelected(false);
        }
        
    }//GEN-LAST:event_tblUserMouseClicked

    private void lblEmptyFnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmptyFnameMouseClicked
        // TODO add your handling code here:
        lblEmptyFname.setForeground(Color.white);
    }//GEN-LAST:event_lblEmptyFnameMouseClicked

    private void lblEmptyLnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmptyLnameMouseClicked
        // TODO add your handling code here:
        lblEmptyLname.setForeground(Color.white);
    }//GEN-LAST:event_lblEmptyLnameMouseClicked

    private void lblEmptyUnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmptyUnameMouseClicked
        // TODO add your handling code here:
        lblEmptyUname.setForeground(Color.white);
    }//GEN-LAST:event_lblEmptyUnameMouseClicked

    private void lblEmptyPwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmptyPwdMouseClicked
        // TODO add your handling code here:
        lblEmptyPwd.setForeground(Color.white);
    }//GEN-LAST:event_lblEmptyPwdMouseClicked

    public void hideLabel(){
        lblEmptyFname.setForeground(Color.white);
        lblEmptyLname.setForeground(Color.white);
        lblEmptyPwd.setForeground(Color.white);
        lblEmptyUname.setForeground(Color.white);
    }
    
    public void populateJtableWithUsers(){
        ArrayList<my_class.Users> usersList = user.usersList();
        
        String[] colNames = {"ID","First Name","Last Name", "Username","Password","Type"};
        Object[][] rows = new Object[usersList.size()][colNames.length];
        
        for(int i = 0; i < usersList.size(); i++){
            rows[i][0] = usersList.get(i).getId();
            rows[i][1] = usersList.get(i).getFirstname();
            rows[i][2] = usersList.get(i).getLastname();
            rows[i][3] = usersList.get(i).getUsername();
            rows[i][4] = usersList.get(i).getPassword();
            rows[i][5] = usersList.get(i).getUserType();

        }
        DefaultTableModel model = new DefaultTableModel(rows,colNames);
        tblUser.setModel(model);
    }        
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JCheckBox chkAdmin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblEmptyFname;
    private javax.swing.JLabel lblEmptyLname;
    private javax.swing.JLabel lblEmptyPwd;
    private javax.swing.JLabel lblEmptyUname;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblUser;
    private javax.swing.JPasswordField txtCfPwd;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLname;
    private javax.swing.JPasswordField txtPwd;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
