/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my_form;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author snamiracle
 */
public class ReturnBookForm extends javax.swing.JFrame {

    /**
     * Creates new form MembersListForm
     */
    
    my_class.Member member = new my_class.Member();
    my_class.Func_Class func = new my_class.Func_Class();
    my_class.Book book = new my_class.Book();
    my_class.Issue_Book issue = new my_class.Issue_Book();
    
    boolean book_exist = false;
    boolean member_exist = false;
    
    
    String imagePath = "";
    
    public ReturnBookForm() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        Border panelHeaderBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(183,77,59));
        jPanel1.setBorder(panelHeaderBorder);
        
        func.displayImage(65, 65,null, "/images/issuebookicon.png", lblTitleMember);
        
        
        setBorderToJlabel(lblBookName, Color.white);
        setBorderToJlabel(lblMemberName, Color.white);
        
        func.customTable(tblIssueBook);
        
        func.customTableHeader(tblIssueBook, new Color(34,167,240),13);
        
        populateJtableWithIssuedBooks("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();
        lblImagePath1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTitleMember = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        dateIssue = new com.toedter.calendar.JDateChooser();
        lblBookName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblMemberName = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dateReturn = new com.toedter.calendar.JDateChooser();
        spBookId = new javax.swing.JSpinner();
        spMemberID = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblIssueBook = new javax.swing.JTable();
        btnLost = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_Status = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();

        lblImage.setBackground(new java.awt.Color(255, 255, 255));
        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setOpaque(true);

        lblImagePath1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblImagePath1.setForeground(new java.awt.Color(0, 51, 255));
        lblImagePath1.setText("choose picture...");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitleMember.setBackground(new java.awt.Color(183, 77, 59));
        lblTitleMember.setFont(new java.awt.Font("AvertaStd-Black", 0, 24)); // NOI18N
        lblTitleMember.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleMember.setText("Return Book");
        lblTitleMember.setAlignmentY(0.0F);
        lblTitleMember.setOpaque(true);

        lblClose.setBackground(new java.awt.Color(183, 77, 59));
        lblClose.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel6.setText("Book ID:");

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel12.setText("Issue Date:");

        btnReturn.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        dateIssue.setEnabled(false);

        lblBookName.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblBookName.setForeground(new java.awt.Color(51, 51, 255));
        lblBookName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBookName.setText("Book Name");
        lblBookName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBookName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBookNameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBookNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBookNameMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel7.setText("Member ID:");

        lblMemberName.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblMemberName.setForeground(new java.awt.Color(51, 51, 255));
        lblMemberName.setText("Member Full-Name");
        lblMemberName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMemberName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMemberNameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMemberNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMemberNameMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel13.setText("Return Date:");

        spBookId.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        spBookId.setEnabled(false);

        spMemberID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        spMemberID.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel14.setText("Note:");

        txtNote.setColumns(20);
        txtNote.setRows(5);
        jScrollPane1.setViewportView(txtNote);

        tblIssueBook.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        tblIssueBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblIssueBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIssueBookMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblIssueBook);

        btnLost.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        btnLost.setText("Lost");
        btnLost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLostActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel8.setText("Select Book Status:");

        jComboBox_Status.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jComboBox_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Issued", "Returned", "Lost" }));
        jComboBox_Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_StatusActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitleMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(7, 7, 7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(dateReturn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dateIssue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spBookId)
                                    .addComponent(spMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBookName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMemberName, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLost, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitleMember, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spBookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(spMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(dateIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(dateReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLost, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        
        int _book_id = (int)spBookId.getValue();
        int _member_id = (int)spMemberID.getValue();
        String note = txtNote.getText();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        try{
            String _return_date = dateFormat.format(dateReturn.getDate());
            Date rtnDate = dateFormat.parse(_return_date);
            
            String _issue_date = dateFormat.format(dateIssue.getDate());
            Date issDate = dateFormat.parse(_issue_date);


            
            if(rtnDate.before(issDate)){
                JOptionPane.showMessageDialog(null, "The return Date must be after Issue date","Wrong Return Date",2);
            }else{
                issue.updateIssue(_book_id, _member_id, "returned", _issue_date, _return_date, note);
                spBookId.setValue(0);
                spMemberID.setValue(0);
                lblBookName.setText("Book Name");
                lblMemberName.setText("Member Full-Name");
                dateIssue.setDate(new Date());
                dateReturn.setDate(new Date());
                txtNote.setText("");
                
            }
            
        } catch(HeadlessException | NullPointerException | ParseException ex){
            JOptionPane.showMessageDialog(null, "Select Issue Date & Return Date","Select Date",2);
        }
    }//GEN-LAST:event_btnReturnActionPerformed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblBookNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBookNameMouseClicked
        // TODO add your handling code here:
        int book_id = (int)spBookId.getValue();
        BookInfoForm bookInfo = new BookInfoForm(book_id);
        bookInfo.setVisible(true);
    }//GEN-LAST:event_lblBookNameMouseClicked

    private void lblMemberNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMemberNameMouseClicked
        // TODO add your handling code here:
        int member_id = (int)spMemberID.getValue();
        MemberInfoForm memberInfo = new MemberInfoForm(member_id);
        memberInfo.setVisible(true);
    }//GEN-LAST:event_lblMemberNameMouseClicked

    private void lblBookNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBookNameMouseEntered
        // TODO add your handling code here:
        setBorderToJlabel(lblBookName, new Color(51,102,255));
    }//GEN-LAST:event_lblBookNameMouseEntered

    private void lblBookNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBookNameMouseExited
        // TODO add your handling code here:
        setBorderToJlabel(lblBookName, Color.white);
    }//GEN-LAST:event_lblBookNameMouseExited

    private void lblMemberNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMemberNameMouseEntered
        // TODO add your handling code here:
        setBorderToJlabel(lblMemberName, new Color(51,102,255));
    }//GEN-LAST:event_lblMemberNameMouseEntered

    private void lblMemberNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMemberNameMouseExited
        // TODO add your handling code here:
        setBorderToJlabel(lblMemberName, Color.white);
    }//GEN-LAST:event_lblMemberNameMouseExited

    private void tblIssueBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIssueBookMouseClicked
        // TODO add your handling code here:
        int index = tblIssueBook.getSelectedRow();
        int book_id = Integer.parseInt(tblIssueBook.getValueAt(index, 0).toString());
        int member_id = Integer.parseInt(tblIssueBook.getValueAt(index, 1).toString());

        
        my_class.Book selectedBook;
        my_class.Member selectedMember;
        
        try {
            selectedBook = book.getBookById(book_id);
            spBookId.setValue(selectedBook.getId());
            lblBookName.setText(selectedBook.getName());
            
            selectedMember = member.getMemberById(member_id);
            spMemberID.setValue(selectedMember.getId());
            lblMemberName.setText(selectedMember.getFirstName() + " " + selectedMember.getLastname());
            
                String issued_date = tblIssueBook.getValueAt(index, 3).toString();
                String return_date = tblIssueBook.getValueAt(index, 4).toString();
                String status = tblIssueBook.getValueAt(index, 4).toString();
                String note = tblIssueBook.getValueAt(index, 5).toString();
            
            Date issDate = new SimpleDateFormat("yyyy-MM-dd").parse(issued_date);
            dateIssue.setDate(issDate);
            
            Date rtnDate = new SimpleDateFormat("yyyy-MM-dd").parse(return_date);
            dateReturn.setDate(rtnDate);
            
            txtNote.setText(note);
            
        } catch (SQLException ex) {
            Logger.getLogger(ReturnBookForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ReturnBookForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblIssueBookMouseClicked

    private void btnLostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLostActionPerformed
        // TODO add your handling code here:
        
        int _book_id = (int)spBookId.getValue();
        int _member_id = (int)spMemberID.getValue();
        String note = txtNote.getText();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        try{
            String _return_date = dateFormat.format(dateReturn.getDate());
            
            String _issue_date = dateFormat.format(dateIssue.getDate());
            
                issue.updateIssue(_book_id, _member_id, "lost", _issue_date, _return_date, note);
                
                int quantity = new my_class.Book().getBookById(_book_id).getQuantity();
                book.setQuantity_Minus_One(_book_id,quantity-1);
                
                
                
                spBookId.setValue(0);
                spMemberID.setValue(0);
                lblBookName.setText("Book Name");
                lblMemberName.setText("Member Full-Name");
                dateIssue.setDate(new Date());
                dateReturn.setDate(new Date());
                txtNote.setText("");
            
        } catch(HeadlessException | NullPointerException ex){
            JOptionPane.showMessageDialog(null, "Select an item from the table","Select Item",2);
        } catch (SQLException ex) {
            Logger.getLogger(ReturnBookForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnLostActionPerformed

    private void jComboBox_StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_StatusActionPerformed
        // TODO add your handling code here:
        String status = jComboBox_Status.getSelectedItem().toString();
//        if(status.equals("All")){
//            status = "";
//        }
        populateJtableWithIssuedBooks(status);
    }//GEN-LAST:event_jComboBox_StatusActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        int index = tblIssueBook.getSelectedRow();
        
        try{
            
            int _book_id = Integer.parseInt(tblIssueBook.getValueAt(index, 0).toString());
            int _member_id = Integer.parseInt(tblIssueBook.getValueAt(index, 1).toString());
            String _issued_date = tblIssueBook.getValueAt(index, 3).toString();   
        
            issue.removeFromIssueTable(_book_id, _member_id, _issued_date);
            
            spBookId.setValue(0);
            spMemberID.setValue(0);
            lblBookName.setText("Book Name");
            lblMemberName.setText("Member Full-Name");
            dateIssue.setDate(new Date());
            dateReturn.setDate(new Date());
            txtNote.setText("");
            
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Select row from table to delete","Delete Error",2);

        }
        
        

    }//GEN-LAST:event_btnDeleteActionPerformed

    public void setBorderToJlabel(JLabel lable, Color color){
        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, color);
        lable.setBorder(border);
    }
    
    public void populateJtableWithIssuedBooks(String _status){
        ArrayList<my_class.Issue_Book> issBooksList = issue.issuedBooksList(_status);
        
        String[] colNames = {"Book","Member","Status","Iss-Date","Rtn-Date","Note"};
        Object[][] rows = new Object[issBooksList.size()][colNames.length];
        
        for(int i = 0; i < issBooksList.size(); i++){
            rows[i][0] = issBooksList.get(i).getBook_id();
            rows[i][1] = issBooksList.get(i).getMember_id();
            rows[i][2] = issBooksList.get(i).getStatus();
            rows[i][3] = issBooksList.get(i).getIssue_date();
            rows[i][4] = issBooksList.get(i).getReturn_date();
            rows[i][5] = issBooksList.get(i).getNote();

            
        }
        DefaultTableModel model = new DefaultTableModel(rows,colNames);
        tblIssueBook.setModel(model);
    }        
    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLost;
    private javax.swing.JButton btnReturn;
    private com.toedter.calendar.JDateChooser dateIssue;
    private com.toedter.calendar.JDateChooser dateReturn;
    private javax.swing.JComboBox<String> jComboBox_Status;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBookName;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImagePath1;
    private javax.swing.JLabel lblMemberName;
    private javax.swing.JLabel lblTitleMember;
    private javax.swing.JSpinner spBookId;
    private javax.swing.JSpinner spMemberID;
    private javax.swing.JTable tblIssueBook;
    private javax.swing.JTextArea txtNote;
    // End of variables declaration//GEN-END:variables
}
